{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"survey_results_schema\",\"power_query_processed\",\"employment_salary\",\"positions\",\"education level\",\"languages sympathy\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.1261.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "ffa7b689-61c9-4ace-8c4c-f5cb4d7e117b",
        "fromColumn": "ResponseId",
        "fromTable": "employment_salary",
        "toColumn": "ResponseId",
        "toTable": "power_query_processed"
      },
      {
        "name": "71526118-1e9a-4403-9bd8-dfd7681c87ad",
        "fromColumn": "ResponseId",
        "fromTable": "positions",
        "toColumn": "ResponseId",
        "toTable": "power_query_processed"
      },
      {
        "name": "ec6cb0d3-8657-4e16-9404-9b9b78d79593",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ResponseId",
        "fromTable": "education level",
        "toColumn": "ResponseId",
        "toTable": "power_query_processed"
      },
      {
        "name": "98fbfd15-3ed6-4d09-bffe-2299aa190611",
        "fromColumn": "ResponseId",
        "fromTable": "languages sympathy",
        "toColumn": "ResponseId",
        "toTable": "power_query_processed"
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "DateTableTemplate_bf015954-52f1-47b3-9924-e75ce572f574",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e2ee283a-58ab-488a-b9bf-8d2b502e638a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fa90ab63-e4a4-484a-ba11-fb69c2045cb5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c143a874-3948-47aa-8e47-ef2ce879b6b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "606b385f-2e30-44e9-8df3-1988bf7d4b81",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "531e41eb-b7fa-4012-bbb5-0efcf920d6fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a2d6ab84-0b95-4b3c-adea-d43eb96f2e03",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bcb5a046-c2dc-43d0-89aa-61d3f7ea6e2f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e7615a47-4951-4c89-ae4d-b74c0f62aea5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d1d61487-c1e3-4c85-bfcb-7025a996dbe9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1754a7b3-b23d-420f-bcd0-74384cb025a3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a3b1ed0a-9999-488e-9415-864b24af13bd",
                "ordinal": 3
              }
            ],
            "lineageTag": "27cc4cf6-e871-4112-bfe4-1f95ad3a765a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "cefe6f87-a2c4-4476-a9d0-b8a52026735e",
        "partitions": [
          {
            "name": "DateTableTemplate_bf015954-52f1-47b3-9924-e75ce572f574",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "survey_results_schema",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "qid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0534c99-7195-47cf-b32a-c1696f71de06",
            "sourceColumn": "qid",
            "summarizeBy": "none"
          },
          {
            "name": "qname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8897979-77f6-420c-945e-dd751c71ed7f",
            "sourceColumn": "qname",
            "summarizeBy": "none"
          },
          {
            "name": "question",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba6cfa50-9b1f-4067-9e8b-12c1b3522324",
            "sourceColumn": "question",
            "summarizeBy": "none"
          },
          {
            "name": "force_resp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab7f843a-40e2-4a82-b7d3-58c31f07aede",
            "sourceColumn": "force_resp",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a281079-d26d-4771-b2c9-6a34f9314364",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "selector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdf2ebbb-4884-4f9c-a811-937cfe318952",
            "sourceColumn": "selector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db86982c-1f0d-4566-9379-90cd9b38ca23",
        "partitions": [
          {
            "name": "survey_results_schema",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Projects\\Stack-overflow-dev-survey-analysis\\data\\survey_results_schema.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"qid\", type text}, {\"qname\", type text}, {\"question\", type text}, {\"force_resp\", type text}, {\"type\", type text}, {\"selector\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "power_query_processed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8eac524-7b32-4f84-8498-81a7f71ed2ea",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "MainBranch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19f91eb8-9843-4107-9db8-820194702d4e",
            "sourceColumn": "MainBranch",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f3c3f0e-ad51-42b5-a099-5b14333361f4",
            "sourceColumn": "Age",
            "summarizeBy": "none"
          },
          {
            "name": "Employment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c6da95b-ec42-420a-9145-65051d1d7c88",
            "sourceColumn": "Employment",
            "summarizeBy": "none"
          },
          {
            "name": "RemoteWork",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ef68ecc-6420-486b-a78e-7f77967deafc",
            "sourceColumn": "RemoteWork",
            "summarizeBy": "none"
          },
          {
            "name": "CodingActivities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80c8ebc3-88af-4717-baeb-2fc677dcae83",
            "sourceColumn": "CodingActivities",
            "summarizeBy": "none"
          },
          {
            "name": "EdLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5003e2d-8175-4d64-878d-24c641d7990c",
            "sourceColumn": "EdLevel",
            "summarizeBy": "none"
          },
          {
            "name": "LearnCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d650e198-0a75-449c-b2aa-cc0f5b8e14f0",
            "sourceColumn": "LearnCode",
            "summarizeBy": "none"
          },
          {
            "name": "LearnCodeOnline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "961d686e-6c9c-4569-9901-c6db6ba4d85c",
            "sourceColumn": "LearnCodeOnline",
            "summarizeBy": "none"
          },
          {
            "name": "LearnCodeCoursesCert",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61afff87-93c5-48d7-a367-fe30e00ce1f3",
            "sourceColumn": "LearnCodeCoursesCert",
            "summarizeBy": "none"
          },
          {
            "name": "YearsCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de308e1c-8b12-4544-b146-993e1ac01fae",
            "sourceColumn": "YearsCode",
            "summarizeBy": "none"
          },
          {
            "name": "DevType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d2220d8-da9b-4102-a3f8-a121259082c2",
            "sourceColumn": "DevType",
            "summarizeBy": "none"
          },
          {
            "name": "OrgSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94ba8170-27d5-4564-88ce-e5574cd04610",
            "sourceColumn": "OrgSize",
            "summarizeBy": "none"
          },
          {
            "name": "PurchaseInfluence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73445a21-784b-4f11-b517-df8499a4f252",
            "sourceColumn": "PurchaseInfluence",
            "summarizeBy": "none"
          },
          {
            "name": "TechList",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b35293b-94e7-4de5-a619-b62ccd8e4cca",
            "sourceColumn": "TechList",
            "summarizeBy": "none"
          },
          {
            "name": "BuyNewTool",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c5ad4de-7eaf-425c-94bf-c71f800396dc",
            "sourceColumn": "BuyNewTool",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45422615-d197-4cc9-a81c-da9f465b1b9c",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dbd8cc3-5ef3-459c-9294-295cef4eb22d",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "CompTotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4b142488-afa1-413e-a294-ec648acc200e",
            "sourceColumn": "CompTotal",
            "summarizeBy": "sum"
          },
          {
            "name": "LanguageHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed3791a1-c228-40b4-8151-df6e90b54269",
            "sourceColumn": "LanguageHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "LanguageWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ca20787-128b-4989-96c5-fcefb636e31a",
            "sourceColumn": "LanguageWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "DatabaseHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2187c9c1-0fd5-4da3-96ac-395716725afb",
            "sourceColumn": "DatabaseHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "DatabaseWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75261dea-282a-4f3c-97f9-7d8368ca5768",
            "sourceColumn": "DatabaseWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "PlatformHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa0004ec-b33e-4b10-94fa-45729421838f",
            "sourceColumn": "PlatformHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "PlatformWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8303cd6a-c5af-4e06-ab06-7329119f6acc",
            "sourceColumn": "PlatformWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "WebframeHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "344194ee-b584-43ba-b093-80efcb6df815",
            "sourceColumn": "WebframeHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "WebframeWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16e03ca9-754a-41ba-aa93-822e6c9d4e95",
            "sourceColumn": "WebframeWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "MiscTechHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43db67e8-e153-4515-95b6-9b67e2001bf1",
            "sourceColumn": "MiscTechHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "MiscTechWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c36e247-305f-4758-bde6-14e077f31cd6",
            "sourceColumn": "MiscTechWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "ToolsTechHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fba8ed78-4429-4ef1-ae52-83a2444fe51e",
            "sourceColumn": "ToolsTechHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "ToolsTechWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55ef285d-e3ae-48cf-b094-7218275bd788",
            "sourceColumn": "ToolsTechWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "NEWCollabToolsHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6c0eb24-3ab2-4f6b-830d-47f5259215c4",
            "sourceColumn": "NEWCollabToolsHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "NEWCollabToolsWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27fa6ee2-85b1-4d0a-95eb-acc17832342f",
            "sourceColumn": "NEWCollabToolsWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "OpSysPersonal use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6ecdffe-90ae-4527-96e0-28285d216cec",
            "sourceColumn": "OpSysPersonal use",
            "summarizeBy": "none"
          },
          {
            "name": "OpSysProfessional use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61342cb1-8eb0-4e96-bd5c-8392221b6338",
            "sourceColumn": "OpSysProfessional use",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackAsyncHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "804236d3-6296-4b2e-9c63-6d01e5967196",
            "sourceColumn": "OfficeStackAsyncHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackAsyncWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d1741a8-edee-4e7b-9d1c-601d7519f8e1",
            "sourceColumn": "OfficeStackAsyncWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackSyncHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60097d6c-ca3e-4f66-a1b5-7aeb21840551",
            "sourceColumn": "OfficeStackSyncHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackSyncWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef1d2c1a-3a45-48f3-a473-f5123194a8b7",
            "sourceColumn": "OfficeStackSyncWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "AISearchHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4595b6ef-31f2-42d8-8dec-a6adf5697ffc",
            "sourceColumn": "AISearchHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "AISearchWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86062c0a-8898-4f36-9806-ba4d7ffe6df6",
            "sourceColumn": "AISearchWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "AIDevHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cff7d95-9a77-41f9-9e5b-81deca4279e1",
            "sourceColumn": "AIDevHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "AIDevWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd4d4d80-87a8-4f26-b52c-8ab75fc14872",
            "sourceColumn": "AIDevWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "NEWSOSites",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "616e5ce4-76b0-4eb4-b040-6820f6158dd7",
            "sourceColumn": "NEWSOSites",
            "summarizeBy": "none"
          },
          {
            "name": "SOVisitFreq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2e5f1bb-62c7-4b75-a385-a65a755ed9bd",
            "sourceColumn": "SOVisitFreq",
            "summarizeBy": "none"
          },
          {
            "name": "SOAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f81d26b-e6b9-4f49-bbd8-bcbe51193eaf",
            "sourceColumn": "SOAccount",
            "summarizeBy": "none"
          },
          {
            "name": "SOPartFreq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d7da6c7-19a0-4eaf-ab06-96fe5db4efce",
            "sourceColumn": "SOPartFreq",
            "summarizeBy": "none"
          },
          {
            "name": "SOComm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "449b1d85-3a2e-4fdb-99e4-39242abb66a2",
            "sourceColumn": "SOComm",
            "summarizeBy": "none"
          },
          {
            "name": "AISelect",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0a2a278-1a59-4c55-8c40-67c04c8e0598",
            "sourceColumn": "AISelect",
            "summarizeBy": "none"
          },
          {
            "name": "AISent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8304aff3-1831-41d1-8cd7-bf9932555d2f",
            "sourceColumn": "AISent",
            "summarizeBy": "none"
          },
          {
            "name": "AIAcc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43c724e8-9c07-4c58-8d45-404774bc0e56",
            "sourceColumn": "AIAcc",
            "summarizeBy": "none"
          },
          {
            "name": "AIBen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e1daf14-ea12-408b-a615-5b2a482cc969",
            "sourceColumn": "AIBen",
            "summarizeBy": "none"
          },
          {
            "name": "AIToolInterested in Using",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "448d11f3-9639-475e-8705-726fac2afd3f",
            "sourceColumn": "AIToolInterested in Using",
            "summarizeBy": "none"
          },
          {
            "name": "AIToolCurrently Using",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce065af7-e0b1-4398-943a-c228790e087a",
            "sourceColumn": "AIToolCurrently Using",
            "summarizeBy": "none"
          },
          {
            "name": "AIToolNot interested in Using",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b72b07b0-9c2a-43bf-aecd-d34b6da2e224",
            "sourceColumn": "AIToolNot interested in Using",
            "summarizeBy": "none"
          },
          {
            "name": "AINextVery different",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daa18606-2039-4dbf-b757-9cdee6e4d0e2",
            "sourceColumn": "AINextVery different",
            "summarizeBy": "none"
          },
          {
            "name": "AINextNeither different nor similar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75bcf39c-19e2-408c-8c77-ccd9c9cb282b",
            "sourceColumn": "AINextNeither different nor similar",
            "summarizeBy": "none"
          },
          {
            "name": "AINextSomewhat similar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dab57d5-c20d-4317-a181-4a93d5b2af66",
            "sourceColumn": "AINextSomewhat similar",
            "summarizeBy": "none"
          },
          {
            "name": "AINextVery similar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cea6bd7-3be1-4665-97af-2d3e6e264ee8",
            "sourceColumn": "AINextVery similar",
            "summarizeBy": "none"
          },
          {
            "name": "AINextSomewhat different",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "766a35d0-7bfa-4dc6-8b0f-3c7ad1683953",
            "sourceColumn": "AINextSomewhat different",
            "summarizeBy": "none"
          },
          {
            "name": "TBranch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de4880f3-8f09-4072-93a1-f8a2a44806d2",
            "sourceColumn": "TBranch",
            "summarizeBy": "none"
          },
          {
            "name": "ICorPM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e424963e-dcdc-4cdb-ab0e-45a57bbc884c",
            "sourceColumn": "ICorPM",
            "summarizeBy": "none"
          },
          {
            "name": "WorkExp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "000ca8a2-defd-41fe-95b5-4dbf392de68c",
            "sourceColumn": "WorkExp",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9fc3ff7-7383-4b28-bb11-9d6d336fe4cc",
            "sourceColumn": "Knowledge_1",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "291b8f38-7133-4f25-8cbd-de0117c961d0",
            "sourceColumn": "Knowledge_2",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bc985d5-8909-4818-bd24-7329b59c1905",
            "sourceColumn": "Knowledge_3",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fb5d6fd-3c35-4148-94bb-853d88a95aa8",
            "sourceColumn": "Knowledge_4",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60ab8ce2-120b-47b6-bdc4-3c7b82c67550",
            "sourceColumn": "Knowledge_5",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "824bbb1b-fb2e-4bb4-8d04-8aa6066e2d63",
            "sourceColumn": "Knowledge_6",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "227ed7f4-9d01-4305-898c-a3f44a66d3b5",
            "sourceColumn": "Knowledge_7",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge_8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf10dedb-e46f-4357-b992-abab0e9fd9b8",
            "sourceColumn": "Knowledge_8",
            "summarizeBy": "none"
          },
          {
            "name": "Frequency_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13633da4-c8ca-4df2-83be-894e2dfc79c1",
            "sourceColumn": "Frequency_1",
            "summarizeBy": "none"
          },
          {
            "name": "Frequency_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dea6b6e0-de9a-467e-9d3c-9d567da4a4dd",
            "sourceColumn": "Frequency_2",
            "summarizeBy": "none"
          },
          {
            "name": "Frequency_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b12f9af1-2c64-4446-b53c-9d8682b1081c",
            "sourceColumn": "Frequency_3",
            "summarizeBy": "none"
          },
          {
            "name": "TimeSearching",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec6dbb1d-d26e-4530-9479-a79b2712a4ec",
            "sourceColumn": "TimeSearching",
            "summarizeBy": "none"
          },
          {
            "name": "TimeAnswering",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "881edf4c-1fca-4d61-b431-74c3b4c9c58a",
            "sourceColumn": "TimeAnswering",
            "summarizeBy": "none"
          },
          {
            "name": "ProfessionalTech",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "973cc8e5-5b2d-475a-a862-bb23516155a3",
            "sourceColumn": "ProfessionalTech",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "357c27b5-9504-461b-8754-098f739d822f",
            "sourceColumn": "Industry",
            "summarizeBy": "none"
          },
          {
            "name": "ConvertedCompYearly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "547ebdb4-7b79-4405-aae6-db36c374ee2d",
            "sourceColumn": "ConvertedCompYearly",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e1663095-646f-4594-afd0-f6f2c1168956",
        "partitions": [
          {
            "name": "power_query_processed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Projects\\Stack-overflow-dev-survey-analysis\\pandas_processed.csv\"),[Delimiter=\",\", Columns=79, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ResponseId\", Int64.Type}, {\"MainBranch\", type text}, {\"Age\", type text}, {\"Employment\", type text}, {\"RemoteWork\", type text}, {\"CodingActivities\", type text}, {\"EdLevel\", type text}, {\"LearnCode\", type text}, {\"LearnCodeOnline\", type text}, {\"LearnCodeCoursesCert\", type text}, {\"YearsCode\", type text}, {\"DevType\", type text}, {\"OrgSize\", type text}, {\"PurchaseInfluence\", type text}, {\"TechList\", type text}, {\"BuyNewTool\", type text}, {\"Country\", type text}, {\"Currency\", type text}, {\"CompTotal\", type text}, {\"LanguageHaveWorkedWith\", type text}, {\"LanguageWantToWorkWith\", type text}, {\"DatabaseHaveWorkedWith\", type text}, {\"DatabaseWantToWorkWith\", type text}, {\"PlatformHaveWorkedWith\", type text}, {\"PlatformWantToWorkWith\", type text}, {\"WebframeHaveWorkedWith\", type text}, {\"WebframeWantToWorkWith\", type text}, {\"MiscTechHaveWorkedWith\", type text}, {\"MiscTechWantToWorkWith\", type text}, {\"ToolsTechHaveWorkedWith\", type text}, {\"ToolsTechWantToWorkWith\", type text}, {\"NEWCollabToolsHaveWorkedWith\", type text}, {\"NEWCollabToolsWantToWorkWith\", type text}, {\"OpSysPersonal use\", type text}, {\"OpSysProfessional use\", type text}, {\"OfficeStackAsyncHaveWorkedWith\", type text}, {\"OfficeStackAsyncWantToWorkWith\", type text}, {\"OfficeStackSyncHaveWorkedWith\", type text}, {\"OfficeStackSyncWantToWorkWith\", type text}, {\"AISearchHaveWorkedWith\", type text}, {\"AISearchWantToWorkWith\", type text}, {\"AIDevHaveWorkedWith\", type text}, {\"AIDevWantToWorkWith\", type text}, {\"NEWSOSites\", type text}, {\"SOVisitFreq\", type text}, {\"SOAccount\", type text}, {\"SOPartFreq\", type text}, {\"SOComm\", type text}, {\"AISelect\", type text}, {\"AISent\", type text}, {\"AIAcc\", type text}, {\"AIBen\", type text}, {\"AIToolInterested in Using\", type text}, {\"AIToolCurrently Using\", type text}, {\"AIToolNot interested in Using\", type text}, {\"AINextVery different\", type text}, {\"AINextNeither different nor similar\", type text}, {\"AINextSomewhat similar\", type text}, {\"AINextVery similar\", type text}, {\"AINextSomewhat different\", type text}, {\"TBranch\", type text}, {\"ICorPM\", type text}, {\"WorkExp\", type text}, {\"Knowledge_1\", type text}, {\"Knowledge_2\", type text}, {\"Knowledge_3\", type text}, {\"Knowledge_4\", type text}, {\"Knowledge_5\", type text}, {\"Knowledge_6\", type text}, {\"Knowledge_7\", type text}, {\"Knowledge_8\", type text}, {\"Frequency_1\", type text}, {\"Frequency_2\", type text}, {\"Frequency_3\", type text}, {\"TimeSearching\", type text}, {\"TimeAnswering\", type text}, {\"ProfessionalTech\", type text}, {\"Industry\", type text}, {\"ConvertedCompYearly\", type text}}),",
                "    #\"Age replace years\" = Table.ReplaceValue(#\"Changed Type\",\"years old\",\"\",Replacer.ReplaceText,{\"Age\"}),",
                "    #\"Age replace years 2\" = Table.ReplaceValue(#\"Age replace years\",\"years\",\"\",Replacer.ReplaceText,{\"Age\"}),",
                "    #\"OrgSize employees replace\" = Table.ReplaceValue(#\"Age replace years 2\",\"employees\",\"\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"CompTotal remove .0\" = Table.ReplaceValue(#\"OrgSize employees replace\",\".0\",\"\",Replacer.ReplaceText,{\"CompTotal\"}),",
                "    #\"CompTotal to decimal\" = Table.TransformColumnTypes(#\"CompTotal remove .0\",{{\"CompTotal\", type number}}),",
                "    #\"ConvertedComp remove .0\" = Table.ReplaceValue(#\"CompTotal to decimal\",\".0\",\"\",Replacer.ReplaceText,{\"ConvertedCompYearly\"}),",
                "    #\"ConvertedComp to decimal\" = Table.TransformColumnTypes(#\"ConvertedComp remove .0\",{{\"ConvertedCompYearly\", type number}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"ConvertedComp to decimal\",\"2 to 9\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"10 to 19\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "483ec3f22a5248ecb002028ba1d74ef1"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6a8727f5-5d51-4af9-ad61-d1145cd1da58",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c909f9e3-8d7f-445d-8bd6-8730928b3cb2",
        "measures": [
          {
            "name": "BG Transparent",
            "expression": "\"rgba(255,255,255,0)\"",
            "lineageTag": "4348f7af-867f-4bc3-9f8c-432d850a48b7"
          },
          {
            "name": "Median employment",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(MEDIANX(values(employment_salary[ResponseId]), calculate(average(employment_salary[ConvertedCompYearly]))), employment_salary[ConvertedCompYearly]>0)",
            "lineageTag": "4b4157e0-402d-40c9-af6a-217f3fd1457b"
          },
          {
            "name": "Selected Country Card",
            "expression": "if(ISFILTERED(positions[Country]), SELECTEDVALUE(positions[Country], \"-\"), \"-\")",
            "lineageTag": "97bd1243-736a-44e0-ace9-60e59bcb0ff2"
          }
        ],
        "partitions": [
          {
            "name": "Measures table",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "employment_salary",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2b1f619d-cc7d-434a-bf50-03d6317e9f78",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "MainBranch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b337fe28-a733-40d6-be76-f6fbf23323a0",
            "sourceColumn": "MainBranch",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dddb4e5-52a5-46e6-812b-3dc882a68ae3",
            "sourceColumn": "Age",
            "summarizeBy": "none"
          },
          {
            "name": "Employment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c2ceea3-50be-4b2e-8bcd-df47967e3a9e",
            "sourceColumn": "Employment",
            "summarizeBy": "none"
          },
          {
            "name": "RemoteWork",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fa1fcad-1921-49e3-b5a1-72ae9f6aec3b",
            "sourceColumn": "RemoteWork",
            "summarizeBy": "none"
          },
          {
            "name": "CodingActivities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9d2212e-ea41-4e24-b949-68d1e7ed9677",
            "sourceColumn": "CodingActivities",
            "summarizeBy": "none"
          },
          {
            "name": "EdLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44fc7b3a-f493-46e4-8d3f-a8d69c72a398",
            "sourceColumn": "EdLevel",
            "summarizeBy": "none"
          },
          {
            "name": "YearsCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "569639ee-5ec9-47da-aab4-68b255e128d4",
            "sourceColumn": "YearsCode",
            "summarizeBy": "none"
          },
          {
            "name": "DevType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ce99ddf-7972-4e99-a005-65c917d1e9ed",
            "sourceColumn": "DevType",
            "summarizeBy": "none"
          },
          {
            "name": "OrgSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cafeb8ce-42a0-4947-bcc1-2c42eea0eed1",
            "sourceColumn": "OrgSize",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6115b7c9-5664-45ae-a83c-a220c11c287c",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "707c744f-aa82-4a33-9a3d-d556f0a942c2",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "CompTotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "150025dc-7366-463b-88bb-fc56141561ae",
            "sourceColumn": "CompTotal",
            "summarizeBy": "sum"
          },
          {
            "name": "LanguageHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "495146e0-155a-4b4b-8344-7f6d8b3fb332",
            "sourceColumn": "LanguageHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "LanguageWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bab60906-42c5-497c-acf3-1a843b1e3a70",
            "sourceColumn": "LanguageWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "DatabaseHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f845f0b0-4984-4c17-91ff-750a7872f558",
            "sourceColumn": "DatabaseHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "DatabaseWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a742540-67b2-4f75-9384-0af294c57533",
            "sourceColumn": "DatabaseWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "PlatformHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c92af47-f1f0-4334-8a02-daa0b42f1b59",
            "sourceColumn": "PlatformHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "PlatformWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a72e272-eaf2-445f-be71-d5bb6749503f",
            "sourceColumn": "PlatformWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "WebframeHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd12a6fe-a9a8-4008-a70f-2ec41a1d0b32",
            "sourceColumn": "WebframeHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "WebframeWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f99c6b56-9496-46d0-98ea-91f6cc567624",
            "sourceColumn": "WebframeWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "MiscTechHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2884871-e7d7-496c-80fa-af40a2c4e445",
            "sourceColumn": "MiscTechHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "MiscTechWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25ef434f-ee05-4b61-870c-6956956447eb",
            "sourceColumn": "MiscTechWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "ToolsTechHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06c48e8a-b7af-4ff3-801a-db4033f05580",
            "sourceColumn": "ToolsTechHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "ToolsTechWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46fbaa61-e025-4014-affc-c69710b35096",
            "sourceColumn": "ToolsTechWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "NEWCollabToolsHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d299a4e1-a2eb-4228-9176-64a635920b79",
            "sourceColumn": "NEWCollabToolsHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "NEWCollabToolsWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8ba599c-7a90-48d4-8b23-09f2af80915e",
            "sourceColumn": "NEWCollabToolsWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "OpSysPersonal use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad5e1d2a-374d-4657-aec4-295c219b79eb",
            "sourceColumn": "OpSysPersonal use",
            "summarizeBy": "none"
          },
          {
            "name": "OpSysProfessional use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1595af0-4481-41ee-a275-6ae44b60db4e",
            "sourceColumn": "OpSysProfessional use",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackAsyncHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd990d3d-ca0e-4e56-bae3-6821a42089da",
            "sourceColumn": "OfficeStackAsyncHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackAsyncWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e51fc8c-3d2b-4673-95bc-97f9bbbc7237",
            "sourceColumn": "OfficeStackAsyncWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackSyncHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b8fed91-2e65-4d08-a32a-24616cad4c98",
            "sourceColumn": "OfficeStackSyncHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeStackSyncWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bb4d1dd-9bbb-4fdf-9c16-674ef37605a8",
            "sourceColumn": "OfficeStackSyncWantToWorkWith",
            "summarizeBy": "none"
          },
          {
            "name": "ICorPM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2c42c2a-d9f9-4cdc-92bb-5f0c08095345",
            "sourceColumn": "ICorPM",
            "summarizeBy": "none"
          },
          {
            "name": "WorkExp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50e7c503-0bc9-4bfb-baea-abf909973af5",
            "sourceColumn": "WorkExp",
            "summarizeBy": "none"
          },
          {
            "name": "ProfessionalTech",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6017e02c-1228-4d66-9fd1-bb82dd91dc41",
            "sourceColumn": "ProfessionalTech",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71fba5b1-f2ce-4d32-9a76-18efe796101d",
            "sourceColumn": "Industry",
            "summarizeBy": "none"
          },
          {
            "name": "ConvertedCompYearly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "69b5a164-0455-4660-89dd-cc7f67f3da1e",
            "sourceColumn": "ConvertedCompYearly",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "dc1417dd-e1c7-4428-bcf4-dc5db4381fce",
        "partitions": [
          {
            "name": "employment_salary",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = power_query_processed,",
                "    #\"Removed Irrelevant Columns\" = Table.RemoveColumns(#\"Source\",{\"PurchaseInfluence\", \"TechList\", \"BuyNewTool\", \"AISearchHaveWorkedWith\", \"AISearchWantToWorkWith\", \"AIDevHaveWorkedWith\", \"AIDevWantToWorkWith\", \"NEWSOSites\", \"SOVisitFreq\", \"SOAccount\", \"SOPartFreq\", \"SOComm\", \"AISelect\", \"AISent\", \"AIAcc\", \"AIBen\", \"AIToolInterested in Using\", \"AIToolCurrently Using\", \"AIToolNot interested in Using\", \"AINextVery different\", \"AINextNeither different nor similar\", \"AINextSomewhat similar\", \"AINextVery similar\", \"AINextSomewhat different\", \"TBranch\", \"Knowledge_1\", \"Knowledge_2\", \"Knowledge_3\", \"Knowledge_4\", \"Knowledge_5\", \"Knowledge_6\", \"Knowledge_7\", \"Knowledge_8\", \"Frequency_1\", \"Frequency_2\", \"Frequency_3\", \"TimeSearching\", \"TimeAnswering\",\"LearnCode\", \"LearnCodeOnline\", \"LearnCodeCoursesCert\"}),",
                "    #\"Split employment by Delimiter\" = Table.SplitColumn(#\"Removed Irrelevant Columns\", \"Employment\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"Employment.1\", \"Employment.2\", \"Employment.3\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split employment by Delimiter\",{{\"Employment.1\", type text}, {\"Employment.2\", type text}, {\"Employment.3\", type text}}),",
                "    #\"Unpivoted Employment\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"ResponseId\", \"MainBranch\", \"Age\", \"RemoteWork\", \"CodingActivities\", \"EdLevel\", \"YearsCode\", \"DevType\", \"OrgSize\", \"Country\", \"Currency\", \"CompTotal\", \"LanguageHaveWorkedWith\", \"LanguageWantToWorkWith\", \"DatabaseHaveWorkedWith\", \"DatabaseWantToWorkWith\", \"PlatformHaveWorkedWith\", \"PlatformWantToWorkWith\", \"WebframeHaveWorkedWith\", \"WebframeWantToWorkWith\", \"MiscTechHaveWorkedWith\", \"MiscTechWantToWorkWith\", \"ToolsTechHaveWorkedWith\", \"ToolsTechWantToWorkWith\", \"NEWCollabToolsHaveWorkedWith\", \"NEWCollabToolsWantToWorkWith\", \"OpSysPersonal use\", \"OpSysProfessional use\", \"OfficeStackAsyncHaveWorkedWith\", \"OfficeStackAsyncWantToWorkWith\", \"OfficeStackSyncHaveWorkedWith\", \"OfficeStackSyncWantToWorkWith\", \"ICorPM\", \"WorkExp\", \"ProfessionalTech\", \"Industry\", \"ConvertedCompYearly\"}, \"Attribute\", \"Value\"),",
                "    #\"Removed attribute\" = Table.RemoveColumns(#\"Unpivoted Employment\",{\"Attribute\"}),",
                "    #\"Renamed value to employment\" = Table.RenameColumns(#\"Removed attribute\",{{\"Value\", \"Employment\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed value to employment\",{\"ResponseId\", \"MainBranch\", \"Age\", \"Employment\", \"RemoteWork\", \"CodingActivities\", \"EdLevel\", \"YearsCode\", \"DevType\", \"OrgSize\", \"Country\", \"Currency\", \"CompTotal\", \"LanguageHaveWorkedWith\", \"LanguageWantToWorkWith\", \"DatabaseHaveWorkedWith\", \"DatabaseWantToWorkWith\", \"PlatformHaveWorkedWith\", \"PlatformWantToWorkWith\", \"WebframeHaveWorkedWith\", \"WebframeWantToWorkWith\", \"MiscTechHaveWorkedWith\", \"MiscTechWantToWorkWith\", \"ToolsTechHaveWorkedWith\", \"ToolsTechWantToWorkWith\", \"NEWCollabToolsHaveWorkedWith\", \"NEWCollabToolsWantToWorkWith\", \"OpSysPersonal use\", \"OpSysProfessional use\", \"OfficeStackAsyncHaveWorkedWith\", \"OfficeStackAsyncWantToWorkWith\", \"OfficeStackSyncHaveWorkedWith\", \"OfficeStackSyncWantToWorkWith\", \"ICorPM\", \"WorkExp\", \"ProfessionalTech\", \"Industry\", \"ConvertedCompYearly\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each true),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\"2 to 9\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"10 to 19\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "positions",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a748082-d056-4491-bfa9-133483d76405",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bf6058e-9db8-4185-b17b-30ddffb0f0ec",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "EdLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "226b8bde-ac67-4023-9b98-a1dcbc9fdb75",
            "sourceColumn": "EdLevel",
            "summarizeBy": "none"
          },
          {
            "name": "DevType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a10fd09-3266-4f22-b813-18ad7457b603",
            "sourceColumn": "DevType",
            "summarizeBy": "none"
          },
          {
            "name": "ConvertedCompYearly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc65e186-4f19-42f5-aa1e-01702725a5ab",
            "sourceColumn": "ConvertedCompYearly",
            "summarizeBy": "sum"
          },
          {
            "name": "language",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9e23787-37a2-431b-9ffc-f55cc87e7e70",
            "sourceColumn": "language",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "188915db-3bf8-4ada-b335-cfe3896a349d",
        "measures": [
          {
            "name": "Median salary",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(MEDIANX(values(positions[ResponseId]), calculate(average(positions[ConvertedCompYearly]))), positions[ConvertedCompYearly]>0)",
            "lineageTag": "2ed0b56a-1fba-46ce-bfb0-47f0b4927c98"
          }
        ],
        "partitions": [
          {
            "name": "positions",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = power_query_processed,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Source\",{\"ResponseId\", \"Country\", \"EdLevel\", \"DevType\", \"LanguageHaveWorkedWith\", \"ConvertedCompYearly\"}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Removed Other Columns\", \"LanguageHaveWorkedWith\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"LanguageHaveWorkedWith.1\", \"LanguageHaveWorkedWith.2\", \"LanguageHaveWorkedWith.3\", \"LanguageHaveWorkedWith.4\", \"LanguageHaveWorkedWith.5\", \"LanguageHaveWorkedWith.6\", \"LanguageHaveWorkedWith.7\", \"LanguageHaveWorkedWith.8\", \"LanguageHaveWorkedWith.9\", \"LanguageHaveWorkedWith.10\", \"LanguageHaveWorkedWith.11\", \"LanguageHaveWorkedWith.12\", \"LanguageHaveWorkedWith.13\", \"LanguageHaveWorkedWith.14\", \"LanguageHaveWorkedWith.15\", \"LanguageHaveWorkedWith.16\", \"LanguageHaveWorkedWith.17\", \"LanguageHaveWorkedWith.18\", \"LanguageHaveWorkedWith.19\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"LanguageHaveWorkedWith.1\", type text}, {\"LanguageHaveWorkedWith.2\", type text}, {\"LanguageHaveWorkedWith.3\", type text}, {\"LanguageHaveWorkedWith.4\", type text}, {\"LanguageHaveWorkedWith.5\", type text}, {\"LanguageHaveWorkedWith.6\", type text}, {\"LanguageHaveWorkedWith.7\", type text}, {\"LanguageHaveWorkedWith.8\", type text}, {\"LanguageHaveWorkedWith.9\", type text}, {\"LanguageHaveWorkedWith.10\", type text}, {\"LanguageHaveWorkedWith.11\", type text}, {\"LanguageHaveWorkedWith.12\", type text}, {\"LanguageHaveWorkedWith.13\", type text}, {\"LanguageHaveWorkedWith.14\", type text}, {\"LanguageHaveWorkedWith.15\", type text}, {\"LanguageHaveWorkedWith.16\", type text}, {\"LanguageHaveWorkedWith.17\", type text}, {\"LanguageHaveWorkedWith.18\", type text}, {\"LanguageHaveWorkedWith.19\", type text}}),",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"ResponseId\", \"Country\", \"EdLevel\", \"DevType\", \"ConvertedCompYearly\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Columns\",{{\"Value\", \"language\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Attribute\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([ConvertedCompYearly] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "education level",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab315a10-f397-4d8f-9e44-e71704c800a4",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "EdLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3620a82-bced-43c9-ad79-077635eb4b58",
            "sourceColumn": "EdLevel",
            "summarizeBy": "none"
          },
          {
            "name": "ConvertedCompYearly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "87e57f1a-a87f-4b9a-9eb0-2a5c644f4618",
            "sourceColumn": "ConvertedCompYearly",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "29b007be-dd57-4d0d-9732-6bd72d190ce7",
        "partitions": [
          {
            "name": "education level",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = power_query_processed,",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Source\",\"2 to 9\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"10 to 19\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Value1\",{\"ResponseId\", \"EdLevel\", \"ConvertedCompYearly\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "languages sympathy",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f5ec59c-274c-4609-9d06-e2f2056ea79e",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "024c72f2-383a-468b-8b1b-01d001a76351",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "ConvertedCompYearly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b485b82-41c5-4f3b-b5d1-b5cd9b5f0f67",
            "sourceColumn": "ConvertedCompYearly",
            "summarizeBy": "sum"
          },
          {
            "name": "LanguageHaveWorkedWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c10a8023-eee3-41e3-98f4-c051469d3cb2",
            "sourceColumn": "LanguageHaveWorkedWith",
            "summarizeBy": "none"
          },
          {
            "name": "LanguagesWantToWorkWith",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5efd749-df86-495d-a43c-ee24663f5aa7",
            "sourceColumn": "LanguagesWantToWorkWith",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c6881ee9-cb8a-4c2a-84e1-3a4d158c59e2",
        "partitions": [
          {
            "name": "languages sympathy",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = power_query_processed,",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Source\",\"2 to 9\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"10 to 19\",\"2 to 19\",Replacer.ReplaceText,{\"OrgSize\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Value1\",{\"ResponseId\", \"LanguageHaveWorkedWith\",\"Country\", \"LanguageWantToWorkWith\", \"ConvertedCompYearly\"}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Removed Other Columns\", \"LanguageHaveWorkedWith\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"LanguageHaveWorkedWith.1\", \"LanguageHaveWorkedWith.2\", \"LanguageHaveWorkedWith.3\", \"LanguageHaveWorkedWith.4\", \"LanguageHaveWorkedWith.5\", \"LanguageHaveWorkedWith.6\", \"LanguageHaveWorkedWith.7\", \"LanguageHaveWorkedWith.8\", \"LanguageHaveWorkedWith.9\", \"LanguageHaveWorkedWith.10\", \"LanguageHaveWorkedWith.11\", \"LanguageHaveWorkedWith.12\", \"LanguageHaveWorkedWith.13\", \"LanguageHaveWorkedWith.14\", \"LanguageHaveWorkedWith.15\", \"LanguageHaveWorkedWith.16\", \"LanguageHaveWorkedWith.17\", \"LanguageHaveWorkedWith.18\", \"LanguageHaveWorkedWith.19\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"LanguageHaveWorkedWith.1\", type text}, {\"LanguageHaveWorkedWith.2\", type text}, {\"LanguageHaveWorkedWith.3\", type text}, {\"LanguageHaveWorkedWith.4\", type text}, {\"LanguageHaveWorkedWith.5\", type text}, {\"LanguageHaveWorkedWith.6\", type text}, {\"LanguageHaveWorkedWith.7\", type text}, {\"LanguageHaveWorkedWith.8\", type text}, {\"LanguageHaveWorkedWith.9\", type text}, {\"LanguageHaveWorkedWith.10\", type text}, {\"LanguageHaveWorkedWith.11\", type text}, {\"LanguageHaveWorkedWith.12\", type text}, {\"LanguageHaveWorkedWith.13\", type text}, {\"LanguageHaveWorkedWith.14\", type text}, {\"LanguageHaveWorkedWith.15\", type text}, {\"LanguageHaveWorkedWith.16\", type text}, {\"LanguageHaveWorkedWith.17\", type text}, {\"LanguageHaveWorkedWith.18\", type text}, {\"LanguageHaveWorkedWith.19\", type text}}),",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"ResponseId\", \"LanguageWantToWorkWith\", \"Country\", \"ConvertedCompYearly\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Columns\",{{\"Value\", \"LanguageHaveWorkedWith\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Attribute\"}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Removed Columns\", \"LanguageWantToWorkWith\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"LanguageWantToWorkWith.1\", \"LanguageWantToWorkWith.2\", \"LanguageWantToWorkWith.3\", \"LanguageWantToWorkWith.4\", \"LanguageWantToWorkWith.5\", \"LanguageWantToWorkWith.6\", \"LanguageWantToWorkWith.7\", \"LanguageWantToWorkWith.8\", \"LanguageWantToWorkWith.9\", \"LanguageWantToWorkWith.10\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"LanguageWantToWorkWith.1\", type text}, {\"LanguageWantToWorkWith.2\", type text}, {\"LanguageWantToWorkWith.3\", type text}, {\"LanguageWantToWorkWith.4\", type text}, {\"LanguageWantToWorkWith.5\", type text}, {\"LanguageWantToWorkWith.6\", type text}, {\"LanguageWantToWorkWith.7\", type text}, {\"LanguageWantToWorkWith.8\", type text}, {\"LanguageWantToWorkWith.9\", type text}, {\"LanguageWantToWorkWith.10\", type text}}),",
                "    #\"Unpivoted Columns1\" = Table.UnpivotOtherColumns(#\"Changed Type2\", {\"ResponseId\", \"ConvertedCompYearly\", \"Country\", \"LanguageHaveWorkedWith\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Unpivoted Columns1\",{{\"Value\", \"LanguagesWantToWorkWith\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"Attribute\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns1\", each ([ConvertedCompYearly] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}